---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
#  - repo: https://github.com/pre-commit/mirrors-pylint
#    rev: v3.0.0a5
#    hooks:
#      - id: pylint
#        language: system
#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: 'v1.9.0'  # Use the sha / tag you want to point at
#    hooks:
#      - id: mypy
#        language: system
#  - repo: https://github.com/pre-commit/mirrors-yapf
#    rev: 'v0.32.0'  # Use the sha / tag you want to point at
#    hooks:
#    -   id: yapf
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.4
    hooks:
      - id: ruff
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
  - repo: https://github.com/Lucas-C/pre-commit-hooks-markup
    rev: v1.0.1
    hooks:
      - id: rst-linter
